### ISSUE TITLE
Why marshal the Context in codemeta2cff?

### ISSUE THREAD

**Issue by broeder-j** [caltechlibrary/datatools#12]
Hi, overall thanks for your nice work. I tried out the codemeta2cff.

In my codemeta files @context is an array (can be nested in general and not a simple string). which fails, since codemeta.go assumes it to be a string.

I was wondering why you need to parse the @context part at all since it is not represented in the Citation.cff?

**Comment by rsdoiel** [comment]
Good Morning, thanks for bringing this up. The short answer is datatools has grown largely around Caltech Library's data practices. We've use the "@context" to help identify when the codemeta.json version. Our Go struct is modeled after the JSON generated at https://codemeta.github.io/codemeta-generator/. As a result I was not aware that I should support "@context" as an array until you pointed it out. Thank you.

In reading [Codemeta Paper](https://github.com/codemeta/codemeta-paper) the text defining "context" seems to suggest singular and the example shows an array. The JSON-LD docs I've read appear ambigous too.

If I use the array example form from the codemetar paper in my codemeta.json for datatools and tried to validate it in the validator. It throughs an error,

```
 @context must be "https://doi.org/10.5063/schema/codemeta-2.0", not ["http://purl.org/codemeta/2.0","http://schema.org"]
```

I like the idea that is links to a DOI because that is very specific.  I am open to supporting more variation but don't have time right now to code the more complex solution. What ever the codemeta tooling produces needs to validate as our patrons and colleagues expect that when they create their own codemeta.json files.

I've flagged this as a bug/help wanted and would am very open to pull requests if you or someone else is inclined.

All the best, 

Robert

**Comment by rsdoiel** [comment]
I no longer think codemeta2cff makes sense. I am considering deprecating it in a future release of datatools. There is such ambiguity in the spec and divergence from practice it makes more sense to work with a template language like Pandoc full transforming codemeta.json into something like CITATION.cff or an about page or version.go. See https://github.com/caltechlibrary/codemeta-pandoc-examples.

**Comment by broeder-j** [comment]
@rsdoiel Hi Robert, thanks for clarification. Makes sense. Using pandoc is an interesting idea.

Meanwhile, just to let you know: we started working on a tool  (https://github.com/Materials-Data-Science-and-Informatics/somesy) to sync metadata in the different metadata files which exist, since we do not want to/can force a user (research software devs) to always use the codemeta.json as single source of truth and generate all the other files from it.
Also there is not a full overlap of the metadata of all these files....

Anyway, if you have some suggestions for that, that saves us time and effort let us know. Thx!

**Comment by rsdoiel** [comment]
A colleague of mine, Mike Hukka, wrote an interesting tool you might want to be aware of (it's in Python) called iga

https://github.com/caltechlibrary/iga

It collects various metadata sources including what is available from the Git repository.

Thanks,

Robert

**Comment by broeder-j** [comment]
That looks like a special case of https://github.com/hermes-hmc/workflow
https://project.software-metadata.pub/, which started at the end of 2021 or so.

i.e. where they have generalized this kind of uploads into repos. You have a command line tool and configure it to upload from anything to anywhere. currently there is special support for github, gitlab as a base to zenodo/invenioRDM, also they are working on dataverse support currently, others to come.
It started with software publications, but the tool is quite general and one could use it to package data sets with metadata or other things also.

**Comment by mhucka** [comment]
Hi – 

Regarding HERMES: we became aware of HERMES earlier this year, and are in touch with the HERMES folks now. Although there is some overlap with HERMES, IGA is not really a special case and doesn't directly compete.

Regarding metadata overlap between the different source: you may be interested in my detailed description of how IGA interprets different sources:

* [Google Spreadsheet](https://docs.google.com/spreadsheets/d/1QgFrZIhip1qKA_M45QkeYe9SH238XL1K/edit?amp;ouid=111701691832013929970&amp;rtpof=true&amp;sd=true#gid=924965025)
* [More readable summary](https://caltechlibrary.github.io/iga/appendix.html)

IGA doesn't handle Python-specific files like setup.cfg (even though IGA is written in Python) because starting down that road would soon lead to requests for handling JavaScript configuration files, Julia files, Rust, etc., and we don't have the resources to go that far :-). So it focuses on `codemeta.json`, `CITATION.cff`, and the metadata available from GitHub's API for releases, users, and repositories.

Regarding somesy: interesting project! Thank you for mention it – I will definitely look more closely at this. I see from skimming the README file that you've faced some similar issues as IGA faced, such as disambiguating person identities. As I'm sure you know, there are some quite challenging edge cases. IGA, for example, needs to get people's names in split form (i.e., first name + last name) because that's what InvenioRDM requires. IGA tries various heuristic approaches to get that. For example, if an ORCID is available but the name is not, it will fetch the person's record from ORCID if it's publicly readable. The worst case is if nothing else is available and the only data available comes from the GitHub user account data (which, among other problems, is very limited and only has a single string for the person's name – if it's even a person and not an organization or bot account); then, IGA still goes the extra mile by trying to split the name string heuristically using machine-learning based methods. I'm still trying to think of ways of improving this process and so am definitely interested in seeing what somesy does in this area.

**Comment by broeder-j** [comment]
Hi @mhucka! Thanks a lot for the detailed explanation.  

I will take a closer look at IGA, the 'make sense' of names functionality is interesting for a project of mine, 
where we aggregate metadata and where we have to deal for software with what mess we get from git repositories sometimes. And I hope to solve some of these issues within the larger data context.

I think with somesy the choice they made on where to draw the line is: that they do not decide themselves of what is wrong or right, beyond some conventions of when to merge for example author properties. They will just warn/error if things are not consistent and they expect the relevant part of the metadata to come from user input and not be auto generated.

Example:
in one file an author has a name and orcid in an other file just a name. Usually a name is not a unique identifier, in a repository they assume it is, as long it occurs once. So they sync the orcid in this case.

But if there are the same orcids in two files (or the same), for a person with a different name. It will raise a warning or error about that, and expects the user then to fix this.  Because to know what orcid is right or wrong it would need to do some of the things you do in IGA. i.e connecting to the outside world and dealing with names in general.
